const companies_investment = [{
    id: 1,
    accordion: 'One', 
    name: 'Solar',
    city: 'São Paulo',
    state: 'SP',
    reason: 'Expansão',
    type: 'Solar',
    investment: 'R$10000',
    value: 'R$2000',
    price: 'R$100',
    financial_return: '11%',
    cnpj: '000000',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
    image: '../images/solar-energy.png'
},
{
    id: 2,
    accordion: 'Two', 
    name: 'Eólica Offshore',
    city: 'São Paulo',
    state: 'SP',
    reason: 'Criação',
    type: 'Eólica Offshore',
    investment: 'R$10000',
    value: 'R$2000',
    price: 'R$100',
    financial_return: '11%',
    cnpj: '000000',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
    image: '../images/wind-offshore.png'
},
{
    id: 3,
    accordion: 'Three', 
    name: 'Eólica',
    city: 'São Paulo',
    state: 'SP',
    reason: 'Se manter no mercado',
    type: 'Eólica',
    investment: 'R$10000',
    value: 'R$2000',
    price: 'R$100',
    financial_return: '11%',
    cnpj: '000000',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
    image: '../images/wind.png'
}
]


const companies_hire = [
{
    name: 'CC BELEM',
    city: 'São Paulo',
    state: 'SP',
    type: 'Eólica',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
},
{
    name: 'CC BELEM',
    city: 'São Paulo',
    state: 'SP',
    type: 'Eólica',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
},
{
    name: 'CC BELEM',
    city: 'São Paulo',
    state: 'SP',
    type: 'Eólica',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
},
{
    name: 'CC BELEM',
    city: 'São Paulo',
    state: 'SP',
    type: 'Eólica',
    email: 'exemplo@email.com',
    tel: '(99)99999-9999',
    responsible: 'Fulano',
}
]